project:
  type: website
  output-dir: docs
  
website:
  page-navigation: true
  title: "MPC School Segregation Collaborative Report"

  sidebar: 
    logo: img/mpc_logo.png
    pinned: true
    align: center
    tools:
        - icon: github
          href: https://github.com/frumh002
  
    style: "docked"
    search: false
    collapse-level: 1
    contents: 
      - href: index.qmd
        text: Home
      - cbsademographics.qmd
      - schoolsegdesc.qmd
      - schoolsegindex.qmd
      - schoolclosures.qmd
      - ecological.qmd
      - suppmaterials.qmd
    
format:
  html:
    theme:
      light: [cosmo, theme.scss]
    code-copy: false
    code-overflow: wrap
    toc: true
    