project:
  type: website
  output-dir: docs
  
website:
  page-navigation: true
  title: "MPC School Segregation Collaborative Report"

  sidebar: 
    logo: img/mpc_logo.png
    pinned: true
    align: center
    tools:
        - icon: github
          href: https://github.com/frumh002
  
    style: "docked"
    search: false
    collapse-level: 1
    contents: 
      - href: index.qmd
        text: Home
      - href: cbsademographics.qmd
        text: Demographics
      - href: schoolsegdesc.qmd
        text: Descriptive Schools
      - href: schoolsegindex.qmd
        text: Segregation Indices
      - href: schoolclosures.qmd
        text: School Closures
      - href: ecological.qmd
        text: Ecological Analysis
      - href: suppmaterials.qmd
        text: Appendix
    
format:
  html:
    theme:
      light: [cosmo, theme.scss]
    code-copy: false
    code-overflow: wrap
    toc: true
    